# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Scripts
email: usmanaura47@gmail.com
description: "Web Scripts develops scripts, plugins, themes and a lot of code that powers the web using technologies like php, python, html, css, javascript, jquery etc"
  
baseurl: "/web-scripts" # the subpath of your site, e.g. /blog
url: "https://usmanaura47.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Malik Usman Aura
copyright:
   name: Malik Usman Aura
   link: 'https://leosoftwares4u.tk'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: ""

# Comments
disqus-shortname: webjeda-demo

#social
facebook: http://facebook.com/webjeda
quora: http://quora.com/sharathdt
twitter: http://twitter.com/@webjeda
github: http://github.com/webjeda

#facebook like box
fb-app-id: ""
fb-page-url: https://www.facebook.com/webjeda/
fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

