# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Scripts
email: usmanaura47@gmail.com
description: "Web Scripts develops scripts, plugins, themes and a lot of code that powers the web using technologies like php, python, html, css, javascript, jquery etc"
  
baseurl: "" # the subpath of your site, e.g. /blog. Note no / at the end
url: "https://usmanaura47.github.io" # the base hostname & protocol for your site

#sidebar
default-image: logo-big.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
copyright:
   name: 'Malik Usman Aura'
   

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: ""

#social
facebook: http://facebook.com/
twitter: http://twitter.com/@malikusmanaura
github: http://github.com/usmanaura47
linkedin: http://linkedin.com

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

