- menu_name: "Services"

- name: "Contact"
  url: "/web-scripts/contact/"
  title: "Contact"

- name: "RSS"
  url: "/web-scripts/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/web-scripts/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/web-scripts/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
